### ISSUE TITLE
【API】简评优化

### ISSUE THREAD

**Issue by anoric** [NewBeeTech/leao-stock-wx#26]
![image](https://user-images.githubusercontent.com/41508689/58113631-93b29080-7c28-11e9-9346-021c52523ed3.png)
----
1. 股东人数减少17.44%，移除负号「-」， 保留两位小数

2. rps数据小了100倍，应乘100

3. 调整roe正向评价条件，当最新roe>40时，不展示正向评价
![image](https://user-images.githubusercontent.com/41508689/58113887-26532f80-7c29-11e9-9348-9014076e66c2.png)

4. 移除销售收现比正向评价
![image](https://user-images.githubusercontent.com/41508689/58116587-44239300-7c2f-11e9-8a9a-dfa12ca7f2cc.png)

5. 调整资产负债率负向评价阈值为60%，此外，当股票行业为'银行/保险/证券/房地产开发'时，不展示此负面评价
![image](https://user-images.githubusercontent.com/41508689/58114099-a1b4e100-7c29-11e9-8ec6-204c4d4277ae.png)

**Comment by liuyangkissu** [comment]
已搞
