### ISSUE TITLE
PEG数据展示优化

### ISSUE THREAD

**Issue by anoric** [NewBeeTech/leao-stock-wx#52]
当PEG数据为空时，现在什么都没有，应该统一显示“--”

![IMG_CB8A80B7B268-1](https://user-images.githubusercontent.com/41508689/58956774-cb493d00-87d1-11e9-9da4-92cf6c150da4.png)

**Comment by liuyangkissu** [comment]
最好在数据层面是做修改，现在为空时数据为空，
![image](https://user-images.githubusercontent.com/26295632/59154572-6e86a480-8aa7-11e9-83e2-99407eeb863e.png)，能不能改成为空是格式为{"year":["2019","2020","2021"],"value":["--","--","--"]}
