### ISSUE TITLE
API - 简评 - 生成逻辑汇总

### ISSUE THREAD

**Issue by anoric** [NewBeeTech/leao-stock-wx#66]
简评问题梳理
 - 估值
   - 正面:(正常)
   - 负面:阈值从65%调整为75%
 - 现金
   - 正面:数值后方增加百分号'%'
   - 负面:数值后方增加百分号'%'
 - 运营
   - 正面:貌似未生效
   - 负面:貌似未生效
 - 商誉
   - (无正面评价)
   - 负面:貌似未生效
 - 质押
   - (无正面评价)
   - 负面:貌似未生效
 - RPS
   - 正面:百分数保留两位小数
   - 负面:当RPS为空时，简评中不应提示该股票弱势; 负面评价时，显示的数值应为(1 - 'rps数值'); 百分数保留两位小数
 - 基金
   - 正面:百分数保留两位小数
   - 负面:百分数保留两位小数; 数值后方增加百分号'%'
 - 户数
   - 正面:(正常)
   - 负面:貌似未生效
 - ST
   - (无正面评价)
   - 负面:貌似未生效

**Comment by liuyangkissu** [comment]
done
